# Generated by Django 5.2.8 on 2025-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound to the University'), ('OUTBOUND', 'Outbound to dropoff')], default='INBOUND', max_length=10),
        ),
    ]
