# Generated by Django 5.2.8 on 2025-11-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancelog_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_valid_from', models.DateTimeField()),
                ('request_valid_until', models.DateTimeField()),
                ('reason', models.TextField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_requests', to='api.student')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
