# Generated by Django 5.2.8 on 2025-11-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_buspassrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buspassrequest',
            old_name='request_valid_from',
            new_name='requested_valid_from',
        ),
        migrations.RenameField(
            model_name='buspassrequest',
            old_name='request_valid_until',
            new_name='requested_valid_until',
        ),
    ]
