# Generated by Django 5.2.8 on 2025-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_request_valid_from_buspassrequest_requested_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspassrequest',
            name='approved_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buspassrequest',
            name='approved_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
